name = "energy-calculator"
main = "dist/_worker.js"
compatibility_date = "2024-01-01"
account_id = "245fab287922ecb490d74c4037bfe793"

[build]
command = "npm run build"

# Uncomment if you need environment variables
# [vars]
# MY_VARIABLE = "production_value"

# Uncomment to add routes
# [[routes]]
# pattern = "example.com/*"
# zone_name = "example.com"